spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_manager
    username: postgres
    password: Psql@1234!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080
application:
  name: finanace_manager
  security:
    jwt:
      secret: 8OPsktHrRkupT3lywWvs8cUfFlL5MqQPO33nWQt621A
      expiration: 86400000